data:
  image: busybox
  volumes:
    - /home/ubuntu/projects/docker-performance-apache-php7-mariadb/backend:/var/www/html

maria_data:
  image: busybox
  volumes:
    - /home/ubuntu/projects/docker-performance-apache-php7-mariadb/maria/data:/var/lib/mysql

php_apache:
  build: ./php7
  extra_hosts:
    - "performance.dev:127.0.0.1"
  links:
    - maria
  volumes_from:
    - data
  environment:
    SYMFONY_ENV: dev
  ports:
    - "80:80"

maria:
  image: mariadb:10.1.20
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  ports:
    - "3306:3306"
